language: java
env:
  global:
  - secure: E9q9OjPHX1EngKg68mPFhZGgcwRpk+P9aujnxqRd22DyYkxktD38wK8MOAb+dhy7h0aAfnCXf2LXzdM8Fevwz2Ppz7DAoe+Z9RN8oBxzPk+lkK7qVCGhQ//GKpS2lKuR10nrue9qu3LNUk1KaJ+tcTkGOQN7zOkCqTraEQE77os=
  - secure: F/PWQpOG1NMfGYjBBz/DjtSBaqWoKxv1kGWrmAxbMjf6obA8maIVPRGuKylcO5T4YTFojl9MK1Zz7OQdqCLHJNBu104MRt8tQHqUwGwsty9xDMvWJ+O0utHrogkEVo5FrZrUj4Jb7iwwiHroaAqqiRkfMHlXFsXq0A5L0M3tl0s=
  - secure: HTnv7vROVcySijtu9C4RfyaY+9CF5Nk9F/y+aiSrLQV4JbM3sMTVEBknhcxRzJbB32O2dRvlaoMjqjp89rRV/2KwepevISWoiU9oYccKqoBZQ6gWt/ms1cUiTNYggDbvztfNggmZ9UNVnVBBb9H6kdAze5g1ANeDZ7Tfljm63rw=
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9cb8d6eff452_key -iv $encrypted_9cb8d6eff452_iv
  -in gpg.tar.enc -out gpg.tar -d
- tar xvf gpg.tar
install: mvn install -DskipTests=true -V
script: mvn test
after_success:
- mvn package gpg:sign -DskipTests=true --settings ./settings.xml
