language: java
env:
  global:
  - secure: E9q9OjPHX1EngKg68mPFhZGgcwRpk+P9aujnxqRd22DyYkxktD38wK8MOAb+dhy7h0aAfnCXf2LXzdM8Fevwz2Ppz7DAoe+Z9RN8oBxzPk+lkK7qVCGhQ//GKpS2lKuR10nrue9qu3LNUk1KaJ+tcTkGOQN7zOkCqTraEQE77os=
  - secure: F/PWQpOG1NMfGYjBBz/DjtSBaqWoKxv1kGWrmAxbMjf6obA8maIVPRGuKylcO5T4YTFojl9MK1Zz7OQdqCLHJNBu104MRt8tQHqUwGwsty9xDMvWJ+O0utHrogkEVo5FrZrUj4Jb7iwwiHroaAqqiRkfMHlXFsXq0A5L0M3tl0s=
  - secure: fNgkGOVg+XjeBLLAd8sk9XwsUF3JpseaIimvnapa0L8+FuIP48n0JPAa+5VcxzpFwkGntK6PTIuTA3tp+C4jWO+HI4p4eoEGqJuIrOhtoFeibT/utfm2GSXmOni5fJ9fOe8r9vYpWJ0LVLoNy5Q6sif/5uevXB18XvMZMRxhTO8=
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9cb8d6eff452_key -iv $encrypted_9cb8d6eff452_iv
  -in gpg.tar.enc -out gpg.tar -d
- tar xvf gpg.tar
install: mvn install -DskipTests=true -V --settings ./settings.xml
script: mvn test --settings ./settings.xml
