language: java
env:
  global:
  - secure: E9q9OjPHX1EngKg68mPFhZGgcwRpk+P9aujnxqRd22DyYkxktD38wK8MOAb+dhy7h0aAfnCXf2LXzdM8Fevwz2Ppz7DAoe+Z9RN8oBxzPk+lkK7qVCGhQ//GKpS2lKuR10nrue9qu3LNUk1KaJ+tcTkGOQN7zOkCqTraEQE77os=
  - secure: F/PWQpOG1NMfGYjBBz/DjtSBaqWoKxv1kGWrmAxbMjf6obA8maIVPRGuKylcO5T4YTFojl9MK1Zz7OQdqCLHJNBu104MRt8tQHqUwGwsty9xDMvWJ+O0utHrogkEVo5FrZrUj4Jb7iwwiHroaAqqiRkfMHlXFsXq0A5L0M3tl0s=
  - secure: YCLtSdVr98XDlDKOeztGLOkO++8iqchha+adqvm/z7ZdjTqGExuNvlHhIgRtOrqm9GfeZeE6tsO6HjMxF2c5QjmzKdZ3l6nE0CKmgOWQoUl1VeD2qwkWPRvUoMQyM3eY91z54BB7Ba2pSBD4XEm+0jdKHmV/1EEwNYaNnEwE0L0=
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9cb8d6eff452_key -iv $encrypted_9cb8d6eff452_iv
  -in gpg.key.enc -out gpg.key -d
install: mvn install -DskipTests=true -B -V
script: mvn test -B
